[package]
name = "mandelbrot"
version = "0.3.0"
authors = ["SwiftViktor <panafviktor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.0"
clap = "3.0.0-beta.2"